version: 1.0
deliver_type: official
owner: master
repo: 172.24.94.60:5000
remote_docker: tcp://39.104.164.56:6066
services:
  demo:
    image: demo/test
    build: C:\work\sdte\local
    ports:
    - 9090
    environment:
    - VERSION=0.0.1
    - SPRING_BOOT_SPRING_CLOUD_CONSUL_HOST=172.24.94.60
    extra_hosts:
    - db.jarvisqh.cn:50.31.209.229
    - zipkin.jarvisqh.cn:50.31.209.229
    deploy:
      deploy_policy: rolling-update
      placement:
        constraints:
        - node.labels.site == Li
      replicas: 1
nodes:
  demo-node2:
    ip: 39.104.164.56
    username: root
    password: 12345ddD
    docker_port: 6066
    labels:
    - site=Li