version: 1.0
type: official
owner: hao  
services:
  mysql-demo:
    image: mysql
    ports: 
      - 3066:3066
    volumes:
      - /docker/db/demo-db:/var/demo/mysql
    environments:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cmc
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=Mypass1!
    deploy:
      nodes: node1
      policy: on-absence
      replicas: 1
  zipkin:
    image: openzipkin/zipkin
    ports: 
      - 9411:9411
    volumes:
      - /docker/db/demo-db:/var/demo/mysql
    environments:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      nodes: node1
      policy: on-absence
      replicas: 1
  demo:
    image: mctree/demo
    build: Dockerfile-demo
    volumes:
      - /docker/demo:/var/demo/
    environments:
      - VERSION=0.0.1
    extra_hosts:
       - db.jarvisqh.cn:node1
       - zipkin.jarvisqh.cn:50.31.209.229
    links:
      - mysql-demo:db.jarvisqh.cn
    depends_on:
      - mysql-demo
      - zipkin
    deploy:
      nodes: node1,node2
      policy: always
      replicas: 2
nodes:
  demo-node1:
    ip: 39.104.164.56
    username: root
    password: 12345ddD
    dockerPort: 6066
    labels:
      - site=Ki
  demo-node2:
    ip: 39.104.164.56
    username: root
    password: 12345ddD
    docker_port: 6066
    labels:
      - site=Li
  mysql-node:
    ip: 39.104.164.56
    username: root
    password: 12345ddD
    docker_port: 6066
    labels:
      - site=Ki