version: 1.0
deliver_type: official
owner: master
remote_docker: tcp://39.104.164.56:6066
repository:
  url: 172.24.94.60:5000
services:
  mysql-demo:
    image: mysql
    volumes:
    - /root/mysql-demo:/var/demo/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cmc
    - MYSQL_USER=demo
    - MYSQL_PASSWORD=Mypass1!
    deploy:
      placement:
        constraints:
        - node.name == demo-node2
      deploy_policy: on-absence
  demo:
    image: demo/test
    build: C:\work\local
    publish_port: 8080
    ports:
    - 9090
    environment:
    - VERSION=0.0.1
    - SPRING_BOOT_SPRING_CLOUD_CONSUL_HOST=172.24.94.60
    extra_hosts:
    - db.jarvisqh.cn:50.31.209.229
    - zipkin.jarvisqh.cn:50.31.209.229
    depends_on:
    - mysql-demo
    deploy:
      deploy_policy: rolling-update
      stop_timeout: 600
      placement:
        constraints:
        - node.name == demo-node2
      replicas: 1
nodes:
  demo-node2:
    ip: 39.104.164.56
    username: root
    password: 12345ddD
    docker_port: 6066